waddrmgr+wallet: allow account import for simnet wallets
btcsuite/btcwallet pull request #743
Opened 2021-04-15 00:21 UTC by wpaulino

Simnet was previously left out as it didn't have defined HD versions for some of our key scopes. To allow testing importing accounts into simnet wallets, we fall back to use the mainnet HD versions.

This commit also addresses an issue with simnet wallets that would arise whenever ScopedKeyManager.AccountProperties was invoked:
`failed to retrieve account public key: unsupported net SimNet`

2021-04-15 00:21 UTC, wpaulino commented
cc @Roasbeef

2021-04-20 16:57 UTC, Roasbeef requested changes

2021-04-20 16:57 UTC, Roasbeef commented on wallet/import.go
> +	case wire.SimNet:
Why not use the testnet here? IIUC, regtest wasn't affected by this as it fell through to the case above (OG testnet net magic).

2021-04-20 21:15 UTC, Roasbeef approved these changes
LGTM 🦖

2021-04-20 23:32 UTC, Roasbeef commented
```
--- FAIL: TestPrunedBlockDispatcherMultipleQueryPeers (5.00s)
    pruned_block_dispatcher_test.go:497: expected nil err to signal completion
```

2021-04-20 23:45 UTC, wpaulino commented
Might be a one-off flake? Haven't seen it in #744 or locally.

2021-04-21 02:19 UTC, merged