waddrmgr/wallet: synchronize recovery shutdown with locking
btcsuite/btcwallet pull request #774
Opened 2021-10-25 17:54 UTC by buck54321

`(*Wallet).recovery` is the only internal consumer of `(*RecoveryManager).Resurrect`
and `(*Wallet).recoverScopedAddresses`, which together account for all uses
of `(*ScopedKeyManager).DeriveFromKeyPath`. The `(*ScopedKeyManager).mtx` is locked
there, but not the `(*ScopedKeyManager).rootManager.mtx`, which protects
the `cryptoKeyPriv` and `cryptoKeyScript` while being zeroed during `(*Manager).Lock`. There is
some care taken to prevent operations with these keys with the `(*Manager).mtx`
locked, but the actual operations involving the keys are done outside
of the `rootManager.mtx` lock, meaning a `(*Manager).Lock` could occur after
a `(*Manager).IsLocked` check, resulting in a race condition with the keys being zeroed as
they're being read, or even with data being encrypted with a zeroed key. [The race was observed](https://gist.github.com/chappjc/df4637a374fbc067af09e6df3fe3c819)
in testing.

Other approaches were considered. Unfortunately, the `ScopedKeyManager`
cannot forego its own mutex and share the Manager's mutex, since there
are multiple recursions. We could carefully lock `(*Manager).mtx`
only around the places it's used, and check the `(*Manager).locked`
every time after locking and before use, returning an error if
locked, but that's pretty tedious and doesn't solve the larger
issue of synchronizing wallet locking with a clean end of recovery.

This PR does not address the general issue of unsafe uses of the `cryptoKeyPriv`/`cryptoKeyScript` by `ScopedKeyManager`, but does fix the issues that we observed in testing.

2021-12-01 23:44 UTC, Roasbeef commented
> This PR does not address the general issue of unsafe uses of the cryptoKeyPriv/cryptoKeyScript by ScopedKeyManager, but does fix the issues that we observed in testing.

Are these uses isolated to the recovery flow, or elsewhere in the logic?

2021-12-01 23:44 UTC, Roasbeef requested changes
Nice catch! 

IIRC, this also fixes an issue in the `lnd` repo tracker as well.

2021-12-01 23:44 UTC, Roasbeef commented on wallet/wallet.go
> +			<-recoverySync.done
Should also select on the `quit` channel as well so we don't introduce the possibility of things deadlocking here.

2021-12-06 22:40 UTC, buck54321 commented
> > This PR does not address the general issue of unsafe uses of the cryptoKeyPriv/cryptoKeyScript by ScopedKeyManager, but does fix the issues that we observed in testing.
> 
> Are these uses isolated to the recovery flow, or elsewhere in the logic?

The `cryptoKeyPriv` is used unsafely mostly by the `ScopedKeyManager` , where it's referenced as `s.rootManager.cryptoKeyPriv`. The `ScopedKeyManager` and its `rootManager *Manager` do not share their `mtx` . Take, for instance, `(*ScopedKeyManager).NewRawAccount` . The `ScopedKeyManager.mtx` is  locked, and `s.rootManager.IsLocked()`is checked in passing, but the actual operations involving `cryptoKeyPriv` in `(*ScopedKeyManager).newAccount` are **not** done under the `Manager.mtx` lock, allowing e.g. `(*Manager).lock` to run simultaneously.

Similarly, you will find a problem starting at `(*Wallet).ImportPrivateKey`, where the `*ScopedKeyManager` is fetched using `(*Manager).FetchScopedKeyManager`, where the read of the `scopedManagers` is protected by the `Manager.mtx`, but ultimately not `(*ScopedKeyManager).ImportPrivateKey` where the `cryptoKeyPriv` is used.

2022-04-27 19:22 UTC, Roasbeef approved these changes
LGTM 🚓

2022-04-27 19:22 UTC, merged