Bug/rescan datarace
btcsuite/btcwallet pull request #820
Opened 2022-10-15 21:56 UTC by MStreet3

2022-10-21 09:26 UTC, guggero requested changes
Thanks a lot for your work on this! The rescan logic is definitely something that needs to be cleaned up.
But I have to admit, this is very hard to review. All the changes are in a single commit so it's almost impossible to reason about everything at the same time. Even with the new tests added that makes it very hard to make sure no dead lock or new data races are introduced with the changes. And that the formatting doesn't match the rest of the code base doesn't really help the review either.

Can you please split things up a bit more for easier review? Thanks!

2022-10-21 09:26 UTC, guggero commented on chain/mocks_test.go
> +	_                 NeutrinoRescanner    = (*mockRescanner)(nil)
nit: separate the variable definitions and the type assertions into their own groups so the formatting looks a bit less "stretched"?

2022-10-21 09:26 UTC, guggero commented on chain/mocks_test.go
> +	opts ...func(*mockRescanner)) *NeutrinoClient {
nit: add newline after multi-line function definition for better readability.

2022-10-21 09:26 UTC, guggero commented on chain/mocks_test.go
> +		chainParams  = &chaincfg.Params{}
A package global variable called `chainParams` is already defined, can just use that one.

2022-10-21 09:26 UTC, guggero commented on chain/mocks_test.go
> +func (m *mockChainService) GetBlock(
nit: formatting.

2022-10-21 09:26 UTC, guggero commented on chain/neutrino.go
> +		s.newRescanner = func(ropts ...neutrino.RescanOption) NeutrinoRescanner {
nit: line length (tab width should be set to 8 spaces).

2022-10-21 09:26 UTC, guggero commented on chain/neutrino.go
> +	case rescanner := <-s.rescannerCh:
All these changes to the rescan logic are very hard to reason about for a reviewer. Is there any way to split this big commit up into small pieces that logically build upon each other to help understand all the individual changes?

2022-10-24 13:13 UTC, MStreet3 commented
Converting to draft state to address comments from @guggero

2022-10-26 07:07 UTC, MStreet3 commented
See #822

2022-10-26 07:07 UTC, closed without merging