chain: add additional logging around new mempool logic
btcsuite/btcwallet pull request #859
Opened 2023-04-26 20:12 UTC by Roasbeef

In this commit, we start to log how long it takes to load+synchronize the mempool. We also demote some logs to the warn logging level. We've seen these calls fail, seemingly due to active replacement attempts in the mempool.

2023-04-26 20:14 UTC, Roasbeef commented on chain/bitcoind_zmq_events.go
> +			log.Debugf("Reconcliing mempool spends with node " +
Could make a sort of `logExecutionTime` func closure for this and the other instances.

2023-04-27 04:02 UTC, yyforyongyu requested changes
Good stuff!

2023-04-27 04:02 UTC, yyforyongyu commented on chain/bitcoind_rpc_events.go
> +			log.Debugf("Reconcliing mempool spends with node " +
```suggestion
			log.Debugf("Reconciling mempool spends with node " +
```

2023-04-27 04:02 UTC, yyforyongyu commented on chain/bitcoind_zmq_events.go
> +			log.Debugf("Reconcliing mempool spends with node " +
```suggestion
			log.Debugf("Reconciling mempool spends with node " +
```

2023-04-27 20:49 UTC, closed without merging